# Generated by Django 5.2.6 on 2025-09-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('sea', 'Sea Freight'), ('air', 'Air Freight'), ('land', 'Land Freight'), ('other', 'Others')], max_length=10)),
                ('details', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
